### ISSUE TITLE
installation trouble

### ISSUE THREAD

**Issue by jsta** [jimhester/archive#2]
It seems that `archive` is having trouble dealing with my system `libarchive` installation. I am on Ubuntu 16.04 and I initially tried to `apt-get` libarchive-dev` (version 3.1.2). `archive` installation failed almost immediately with the message:

> archive.cpp: In function ‘Rcpp::IntegerVector archive_filters()’:
archive.cpp:61:26: error: ‘ARCHIVE_FILTER_LZ4’ was not declared in this scope
       , Rcpp::_["lz4"] = ARCHIVE_FILTER_LZ4

Then, I built libarchive from source (version 3.3.1). Now the installation proceeds further but ends with this error message:

> Error: package or namespace load failed for ‘archive’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '~/R/x86_64-pc-linux-gnu-library/3.4/archive/libs/archive.so':
~/R/x86_64-pc-linux-gnu-library/3.4/archive/libs/archive.so: undefined symbol: archive_write_set_format_raw
Error: loading failed

Any ideas?

**Comment by jimhester** [comment]
This should now be fixed.
