### ISSUE TITLE
Add compression configuration

### ISSUE THREAD

**Issue by coolbutuseless** [jimhester/archive#22]
Feature request: Expose the individual format/filter configuration options to the R interface i.e. `archive_compressor_[name]_options` and `archive_filter_[name]_options`

For example, `zstd` defaults to compression level 3 and there's no way to configure this from R.

**Comment by jimhester** [comment]
Agreed, we need to expose this.

**Comment by jimhester** [comment]
We now support pass the [write_options](https://www.freebsd.org/cgi/man.cgi?query=archive_write_set_options&sektion=3&format=html) and [read_options](https://www.freebsd.org/cgi/man.cgi?query=archive_read_set_options&sektion=3&format=html) where appropriate.

e.g.

```r
f3 <- tempfile(fileext = ".tar.gz")
write.csv(mtcars, archive_write(f3, "mtcars.csv", options = "compression-level=2"))
```
