### ISSUE TITLE
error in installation 

### ISSUE THREAD

**Issue by NoushinN** [jimhester/archive#24]
Looks like a great package, facing this currently when trying to install: 
ERROR: configuration failed for package ‘archive’
fatal error: 'archive.h' file not found
Any other package dependencies for archive?

**Comment by jimhester** [comment]
Yes, you have to have the appropriate libarchive system library installed.

https://github.com/jimhester/archive/blob/09754896e63a96f928aaacf9528589caba7d6128/DESCRIPTION#L19-L20
