### ISSUE TITLE
Is the Remote specification on glue needed?

### ISSUE THREAD

**Issue by raymondben** [jimhester/archive#25]
I have an appveyor build failing that I don't quite understand: https://ci.appveyor.com/project/raymondben/bowerbird. The failure is related to `archive`: it appears that `glue` is being installed OK from CRAN but then because the github version is newer, and because `archive`'s DESCRIPTION file includes `Remotes: tidyverse/glue`, it then tries to install from github and fails.
Is the `Remotes` spec needed? (Bearing in mind that I am not sure that this is even the problem here. I've tried to discourage appveyor from building glue from source, but that doesn't seem to help)

**Comment by jimhester** [comment]
Not anymore, it has been removed.
