### ISSUE TITLE
Is it possible to unzip .csv.7z files?

### ISSUE THREAD

**Issue by alexhallam** [jimhester/archive#26]
I ran the following reproducible code

```r
library(archive)
tf <- tempfile() ; td <- tempdir()
file.path <- "https://www.kaggle.com/c/favorita-grocery-sales-forecasting/download/holidays_events.csv.7z"
download.file(url = file.path, destfile = tf, mode = "wb")
archive(tf)
```

I get the error

> Error in archive_metadata(path) : Unrecognized archive format

I was wondering if unzipping .csv.7z files was supported.

**Comment by jimhester** [comment]
The URL you are trying to download needs you to be logged in to download it. The content in tf is the login page, not the 7z archive. See `browseURL(tf)`
