### ISSUE TITLE
archive_extract on 7-zip file fails on unix

### ISSUE THREAD

**Issue by ajdamico** [jimhester/archive#3]
hi, thanks for the awesome software.  here's a minimal reproducible example that walks through a file that fails with `archive_extract` but not 7-zip software on unix.  the problem does not occur on windows

	## warning: large download

	# example from the PISA 2015 website to show there's no download or site-specific problem
	fn <- "http://vs-web-fs-1.oecd.org/pisa/PUF_SAS_COMBINED_CMB_SCH_QQQ.zip"

	tf <- tempfile()
	tf2 <- tempfile()

	download.file( fn , tf , mode = 'wb' )

	file.info( tf )
	file.copy( tf , tf2 )

	# works fine
	system(paste0("7za e -o'" , tempdir() , "' '" , tf2 , "'"))
	R.utils::countLines( file.path( tempdir() , "cy6_ms_cmb_sch_qqq.sas7bdat" ) )

	file.remove( file.path( tempdir() , "cy6_ms_cmb_sch_qqq.sas7bdat" ) )

	# works fine
	archive::archive_extract( tf , dir = tempdir() )
	R.utils::countLines( file.path( tempdir() , "cy6_ms_cmb_sch_qqq.sas7bdat" ) )

	file.remove( tf )
	file.remove( tf2 )

	# much larger file from the PISA 2015
	fn <- "http://vs-web-fs-1.oecd.org/pisa/PUF_SAS_COMBINED_CMB_STU_QQQ.zip"

	download.file( fn , tf , mode = 'wb' )

	file.info( tf )
	file.copy( tf , tf2 )

	# works fine
	system(paste0("7za e -o'" , tempdir() , "' '" , tf2 , "'"))
	R.utils::countLines( file.path( tempdir() , "cy6_ms_cmb_stu_qq2.sas7bdat" ) )

	file.remove( file.path( tempdir() , "cy6_ms_cmb_stu_qq2.sas7bdat" ) )

	# FAILS on unix WORKS on windows
	archive::archive_extract( tf , dir = tempdir() )
	# archive_extract() appears to have worked, but the extracted files are all blank
	R.utils::countLines( file.path( tempdir() , "cy6_ms_cmb_stu_qq2.sas7bdat" ) )

**Comment by jimhester** [comment]
This now returns an error `Unsupported ZIP compression method (deflation-64-bit)`
