### ISSUE TITLE
Packing to RAR files

### ISSUE THREAD

**Issue by ManuHamel** [jimhester/archive#33]
Hi,

I tried to pack some file to « .rar » with the archive **R** package  but I was not able to. From my point of view, it would be great if we could add this feature to the archive package.

Best regards,

Emmanuel

**Comment by jimhester** [comment]
Support for rar depends on the upstream [libarchive](https://github.com/libarchive/libarchive) project. It seems writing rar is not supported, however reading from rar 4 archives is.

```r
write.csv(mtcars, "bar.csv")
```

```shell
# brew cask install rar
rar a -ma4 foo.rar bar.csv
```

``` r
read.csv(archive::archive_read(archive = "~/p/archive/foo.rar"))
#>                      X  mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> 1            Mazda RX4 21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
#> 2        Mazda RX4 Wag 21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
#> 3           Datsun 710 22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
#> 4       Hornet 4 Drive 21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
#> 5    Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
#> 6              Valiant 18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
#> 7           Duster 360 14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
...
```

<sup>Created on 2020-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

rar 5 archives seem to have issues with libarchive, see https://github.com/libarchive/libarchive/issues/1426

**Comment by ManuHamel** [comment]
Hi,

Thanks! From my point of view, it would be nice to add the possibility to
write to RAR files.

Best regards,

Emmanuel

Le lun. 28 sept. 2020 à 10:25, Jim Hester <notifications@github.com> a
écrit :

**Comment by wyatt8740** [comment]
@ManuHamel unfortunately the rar licensing terms prohibit this.
