### ISSUE TITLE
Cannot install archive even libarchive-dev is present on Debian

### ISSUE THREAD

**Issue by JackieMium** [jimhester/archive#34]
I've installed `libarchive-dev` on Debian and both `libarchive.pc` and `archive.h` are present, but `archive` installation still complains about missing `archive.h`:

![image](https://user-images.githubusercontent.com/12944832/99741618-9a1b1480-2b0c-11eb-8210-d8b395d3a994.png)

**Comment by jimhester** [comment]
Did you check that `pkg-config` is in your path and that `pkg-config --cflags libarchive` returns something?

**Comment by JackieMium** [comment]
this is odd:

```
➜  ~ which pkg-config 
/usr/bin/pkg-config
➜  ~ pkg-config --version
0.29.2
➜  ~ pkg-config --cflags libarchive 

➜  ~ pkg-config --list-all|grep libarchive
libarchive                     libarchive - library that can create and read several streaming archive formats
```

**Comment by jimhester** [comment]
I don't know, there must be an issue with pkg-config installed in the conda environment or something like that. I don't know anything about conda and in general don't think it is wise to use it with R packages, you will have to get assistance elsewhere.

As I don't believe this is an issue with the archive package I am closing this issue.
