### ISSUE TITLE
archive_extract failure on both unix and windows

### ISSUE THREAD

**Issue by ajdamico** [jimhester/archive#5]
hi, `archive_extract` fails on unix and windows but R's default `unzip()` function succeeds..thank you

	tf <- tempfile()
	download.file( "http://download.inep.gov.br/microdados/micro_enem1998.zip" , tf , mode = 'wb' )

	first_zipped_file <- unzip( tf , exdir = tempdir() )

	second_zipped_file <- grep( "\\.zip$" , first_zipped_file , value = TRUE )

	# works
	windows_unzip <- unzip( second_zipped_file , exdir = tempdir() )
	R.utils::countLines( windows_unzip )
	file.remove( windows_unzip )

	# works
	system(paste0("7za e -o'" , tempdir() , "' '" , second_zipped_file , "'"))
	R.utils::countLines( windows_unzip )
	file.remove( windows_unzip )

	# fails
	archive::archive_extract( second_zipped_file , dir = tempdir() )
	R.utils::countLines( windows_unzip )

**Comment by jimhester** [comment]
This now returns an error `Unsupported ZIP compression method (bzip)`.
