### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by GoChartingAdmin** [jimhester/archive#9]
Do we need to install libarchive-dev before installing this R Package?  Is there a way that all the dependencies can be built within the installation of this R Package.

Currently, when I try to install the package from github, I get the following message

> devtools::install_github("jimhester/archive")
Note: no visible binding for global variable '.Data' 
Downloading GitHub repo jimhester/archive@master
from URL https://api.github.com/repos/jimhester/archive/zipball/master
Installing archive
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpyKaB6I/devtools4a93024acee/jimhester-archive-a203312'  \
  --library='/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

* installing *source* package ‘archive’ ...
PKG_CFLAGS=
PKG_LIBS=-larchive
<stdin>:1:21: fatal error: archive.h: No such file or directory
compilation terminated.
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libarchive was not found. Try installing:
 * deb: libarchive-dev (Debian, Ubuntu, etc)
 * rpm: libarchive-devel (Fedora, CentOS, RHEL)
 * csw: libarchive_dev (Solaris)
 * brew: libarchive (Mac OSX)
If libarchive is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libarchive.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘archive’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2/archive’
Error: Command failed (1)

**Comment by jimhester** [comment]
Yes you need to install `libarchive-dev` on the system.

**Comment by lucasmation** [comment]
Just a clarification on install: 

a) as long as the user has Rtools the installation of the `archive` package will work, in any environment, correct?
b) if I don't have Rtools, or any additional libraries, in my Windows PC `archive` will not work. Correct?

**Comment by jimhester** [comment]
Yes on windows all you should need is Rtools to install the package.
